name: Sync OpenAPI spec to README.com

on:
  push:
    branches:
      - v1.0
    paths:
      - 'reference/openapi.yaml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Push OpenAPI spec to README.com
        run: npx rdme openapi upload reference/openapi.yaml --key ${{ secrets.README_API_KEY }} --slug=openapi
